### ISSUE TITLE
Enforced coercion of integer and float

### ISSUE THREAD

**Issue by simongray** [arachne-framework/aristotle#14]
I was wondering if there is a technical reason why Aristotle converts `Integer` to `XSDlong` and `Float` to `XSDdouble`? Wouldn't it be preferable to map the full breadth of RDF datatypes, especially the ones which are used as literals in e.g. TTL files?

At the moment, you end up with `"1"^^<http://www.w3.org/2001/XMLSchema#long>` rather than `1` even if you _explicitly_ choose to use integers in Clojure rather than longs, since these coercions are applied in the `arachne.aristotle.graph/AsNode` protocol before adding the data to the graph.

**Comment by archie14** [comment]
Hi Simon,

I used this library in the past and recently used parts of this library to suite my own needs. I do expect though you understand the library better than I do. Having said this, could it be that your question is actually two questions?

One being "Why does Aristotle convert Integer to XSDLong?"
The other being "Why does Aristotle store the datatype with the value itself?" 

As far as I can tell, the method createLiteralByValue used by AsNode requires the RDFDatatype. Then again, my understanding of Java code is quite poor. 

I hope this helps. Saw your message the other day and just had to respond. Since I consider Aristotle to be one of the hidden RDF gems available. At the very least within the Clojure community.

**Comment by simongray** [comment]
No, my question is really just the first one: why is Integer/Float being coerced to XSDlong/XSDdouble as opposed to XSDint/XSDfloat?

Clojure's _natural_ integer data type is of course the `Long`, so if you only work in Clojure, primarily use your own data, and never want to interoperate with other RDF environments, coercing everything to the preferred supertype in Clojure (e.g. float->double and int->long) makes it easier to deal with in a Clojure environment (I guess), but it just kinda breaks when you _do_ cross that boundary.

It also differs from how Apache Jena itself intends things to be:

<img width="768" alt="Skærmbillede 2023-05-11 kl  15 54 55" src="https://github.com/arachne-framework/aristotle/assets/1388652/e8349b53-2d49-4ba3-aba1-40578f098831">

I have an entire Turtle dataset that, rather than just using the native RDF integer literal (e.g. `1`), is forced to the awkward `"1"^^<http://www.w3.org/2001/XMLSchema#long>` encoding due to the implicit coercions that Aristotle performs when you add stuff to a graph.
